/// Flutter icons DdishFlutterApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DdishFlutterApp
///      fonts:
///       - asset: fonts/DdishFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class DdishAppIcons {
  DdishAppIcons._();

  static const _kFontFam = 'DdishFlutterApp';

  static const IconData more = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData before = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData location_closed = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData location_open = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData menu = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData next = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData notifications = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData satellite = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData satellite_bg = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData arrow_down = const IconData(0xe80a, fontFamily: _kFontFam);
}
